### ISSUE TITLE
Issue提出：レビュー依頼

### ISSUE THREAD

**Issue by pakira-56A** [pakira-56A/aruaru-game#104]

**Comment by pakira-56A** [comment]
# ■ Webアプリの概要
**トランプゲームや`あるある`ゲームを通じ、友達や新しい出会いを促進するサービス**  
ユーザーが投稿(またはAIで生成した)`界隈のあるある`を、カードに反映。神経衰弱として遊べます！  
メジャーからマニアックまで  
あらゆる界隈の`あるある`を知りつつ、共通の趣味がない人とも交流できる！  
仲良し同士でも新たな一面を発見できたり、神経衰弱が苦手でも楽しめます！  

# ■ １週間辺りの開発に向けられる時間
**調べごとをする時間がかなり多いと思われます。以下の時間には含めてません**
  - **１５**時間（現在首を痛めてまして、長時間座るのもキツいです。治る速さが不明なので少なめに書きました）
  - **２５**時間（完治後の最低限の目標）
**１週間のスケジュールは、一旦前者で組み立てています。**
首が治り次第、25時間を目安にしたTodoに変更する予定です。

# ■ ProjectsのURL
https://github.com/users/pakira-56A/projects/1


# ■ MVPリリースまで
**※Renderでデプロイ済み・トップページのみ作成済みです**（[参考記事(2024.6頃の記載)](https://hackmd.io/@SKjw2RY-RNCUNSdJfEWPig/HJE0GUClC)）  
- [x] トップページの再調整
  - （`モード選択モーダル削除` `左上のトグルをハンバーガーメニューに格納` `利用規約/プライバシーポリシーのモーダルを配置`）
- [x] **`界隈あるある`投稿・編集・削除**
  - **`界隈名`はオートコンプリート機能**で投稿（同じものを指すのに、表記が違うと困惑するため）
  -  投稿された`界隈`一覧（未ログインでも閲覧可能）
  -  投稿された`あるある`を神経衰弱としてプレイできる機能
- [x] **Google ログイン**
  - 名前・メールアドレス・アイコン変更
  - 参考資料：[Googleログインの実装（`devise` + `omniauth`）](https://zenn.dev/tteaoocl/articles/0f0e6443cd318f)

### 本リリースにむけて
- [x] **`あるある`をAIで生成**（未ログインでも閲覧可能）
  -  AIで生成された`あるある`を、神経衰弱としてプレイできる機能（未ログインでも閲覧可能）
- [x] **Xシェア機能**
  - 動的OGP
- [x] **投稿をお気に入り登録/解除**
  - お気に入りの投稿一覧
- [x] **投稿にハッシュタグ（未ログインでも閲覧可能）**
  - ハッシュタグの絞り込み検索・編集・削除
  - [x] **Xシェア時にハッシュタグを用いる**
    - 必須のハッシュタグ #あるある神経衰弱
    - プレイした`界隈`に応じたハッシュタグも必要（界隈例：#ONEPIECE ） 
      - 空白の入力を許可しないバリデーションが必要（界隈例：#ONE` `PIECE だとハッシュタグにならない）

- [x] 利用規約を追記
- [x] プライバシーポリシーを追記
- [x] お問い合わせを追記

- [x] RSpec（モデルテスト・システムテスト）
- [x] CI（GitHubActions）
- [x] 独自ドメイン
- [x] レスポンシブ対応（スマホ重視）

# ■ MVPレビュー依頼予定日
予定日：2024年 10月 13日

**Comment by rdhdchloe** [comment]
対応ありがとうございます。
ストーリーポイントを確認したところ、4ポイント以上のカードが存在するのを確認しました。
カリキュラムにもありましたとおり、ストーリーポイント3以下になるように細かくissue化してください。
細かくissue化することで、不明瞭な箇所、明瞭な箇所が可視化されることに加えて、進捗を感じられながら開発を進めることができます。
対応の上、再提出操作をお願いいたします。

**Comment by pakira-56A** [comment]
有難うございます。、4ポイント以上のカードは、２枚に分けました。
キャッチアップに時間をとられることを考慮し、余裕を持たせたストーリーポイント配分にしてます。
よろしくお願いします

**Comment by tmtkzk0823** [comment]
修正ありがとうございます。
概ね良さそうです！

LGTMです！
