### ISSUE TITLE
24.11.15~18.🟥 MVPのレビューを提出

### ISSUE THREAD

**Issue by pakira-56A** [pakira-56A/aruaru-game#136]
## 各種情報
**サービスの概要とMVPで検証する事柄：** 投稿されたあるあるが神経衰弱として遊べること
**サービス名：** あるある神経衰弱
**サービスURL：** https://aruaru-game.onrender.com/
現在の[README](https://github.com/pakira-56A/aruaru-game?tab=readme-ov-file#)
## READMEレビュー時にMVPリリース時点で実装予定だった機能
チェック済みは実装済みです
- [x] 投稿機能（AIではなくユーザー自ら界隈とあるあるを投稿）
- [x] ゲーム機能：投稿した/された界隈あるあるを神経衰弱に反映
- [x] Googleログイン
- [ ] AI生成機能
- [ ] Xシェア機能
- [ ] 動的OGP：静的は実装済み

## READMEレビュー時から変更した機能
**実装しなかった機能**
- **AI生成機能**
  - 投稿機能で充分遊べるので、この機能は本リリースに回しました
  - ただ、このアプリの実装予定の機能から省いてもいいかも...?という気持ちも少しあります
- **Xシェア機能**・**動的OGP**
  - アプリ概要の最低限の機能ではないので、MVPから除外

**追加した機能**
- 投稿の詳細・編集・削除機能
- ログアウト機能

## サービスイメージがわかるようなスクリーンショット等
管理画面などはありません。
[![Image from Gyazo](https://i.gyazo.com/14944534441356892ede68e3909fbe01.png)](https://gyazo.com/14944534441356892ede68e3909fbe01)
_____
### 講師陣の皆様へ
READMEを提出した際もレビューしていただきありがとうございました。
今回は、技術面談やスケジュール面談にて相談させていただいた
MVPリリース向けの機能(上記)の実装が完了したので提出いたします。
荒削りですが、レビューをよろしくお願いいたします。
（楽しんでもらえると幸いです）
____

**Comment by rdhdchloe** [comment]
ご提出ありがとうございます。
以下コメントになります。

---

以下に、修正・リファクタリングの必要がある箇所をリスト化しました。

### post.rb

- 問題点: バリデーションの繰り返し。
- 改善点: aruaru_oneからaruaru_fiveまでのバリデーションが重複しているため、配列を使ってバリデーションをまとめることができます。


### ファイル名: google_login_api_controller.rb
- 問題点: エラーハンドリングが単純であり、例外の詳細がわかりにくい。
- 改善点: エラーが発生した場合に、ユーザーに適切なメッセージを表示するようにする。
```ruby
    rescue StandardError => e
      pp e
    end
```


### ファイル名: posts_controller.rb
- 問題点: createメソッドとupdateメソッドで同様のバリデーションメッセージを繰り返している。
- 改善点: バリデーションメッセージを定数として定義し、再利用する。

### ファイル名: posts_controller.rb
- 問題点: `destroy`メソッドで`destroy!`を使用しているため、例外が発生した場合の処理がされていない。
- 改善点: `destroy`メソッドをトランザクション内で実行し、エラーハンドリングを追加する。

### ビューファイルの命名やネームケース
- 問題点：ファイル名がわかりにくい。例：myindex.html。またpostsディレクトリ内にありますがusersディレクトリ内に配置すべき。
- 改善点：users/posts/index.html.erbのように配置した方が分かりやすい。


よろしくお願いします！

**Comment by pakira-56A** [comment]
レビューありがとうございます
こちらが問題点を[修正した際のプルリク](https://github.com/pakira-56A/aruaru-game/pull/217#issue-2665227875)になります。
（長くなったのでリンクによる省略をさせていただきました。）
___
**以下の機能を実装しなかった理由**
- **AI生成機能**
  - 最大の理由：投稿機能で十分遊べるため
  - スケジュールの要因
    - README提出後の技術面談などで、年末年始の運営様の運休や、Open AIをキャッチアップする時間を相談しました。
    - 私の卒業認定日は翌年1/10、MVP提出日は12/8と決まり  
       MVPリリースに向けた機能から除外してもよいのではと判断しました。

- **Xシェア機能・動的OGP**
> 承知しました。本リリースまで実装予定でしょうか。

はい、本リリースに向けて実装予定です。
____
よろしくおねがいいたします！

**Comment by kenchasonakai** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。

**Comment by pakira-56A** [comment]
ありがとうございます！！！
以下は今後の認識のため、記載だけさせていただきますね
____
===== 本リリースまでに以下の項目を実装してください（✅は実装済み） =====
- [ ] **独自ドメイン反映**
> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
- [ ] **OGP（静的 or 動的）**
> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。

静的OGPは実装済みです、余裕があれば動的にしたいです。

- [ ] **RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）**
> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
- [ ] **CI（GitHubActions）**
> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
- [ ] **Rubocopを使ってのリファクタリング**
> Lintチェックツールは開発現場で広く使われています。
> コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。
____
他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
　
- [x] **SNSログイン（Google or LINE）**
> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。

Googleログインを実装済みです。

- [ ] **検索機能のアップデート（オートコンプリート、マルチ検索等） ※検索機能がある場合**
> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。
____
ユーザー体験という面では以下の項目も大切です。
- [x] **利用規約・プライバシーポリシーを未ログイン状態でも確認できる**
> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
- [x] **使い方説明がある**
> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
- [ ] **オートログイン**
> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
- [ ] **レスポンシブ対応**
> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
- [ ] **ローディングアニメーション（処理が重い箇所）**
> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。
> そうした際はローディングアニメーションを表示させることで体験が向上します。
