### ISSUE TITLE
24.11.20~21.🟥 本リリースのissue見積もりを提出（11/24まで）

### ISSUE THREAD

**Issue by pakira-56A** [pakira-56A/aruaru-game#220]
**MVPリリース時点**で使っているもの
- Rails 7.1. 、Ruby 3.2.3. 、JavaScript、CSS、Tailwind、DaisyUI、Google認証（devise）

**本リリースに向けて**追加予定のもの
- Stimulus、Open AI

そのキャッチアップ・テスト実装が不安なので、余裕を持った締め日を設定しています。
早めに実装完了した場合は、次のissueを前倒しで実装していく予定です。
（本リリースを終えてから、本格的に就活を始めるのを希望しています）
____
## 🟧 は本リリースに向けて実装する、アプリの機能
**SNSに関して**（〆：12/1 ）
  - [ ] **動的OGP**（静的OGPは実装済みですが、画像を変更したり。動的に変更したい）
    - 参考記事：[【動的OGP】Rails、Dockerを使って X シェアを実装](https://zenn.dev/yukimura_n/articles/1007c5dbedebc1)  
`game.js`ファイルで書いた、ゲームクリア後ダイアログを、モーダルに書き換え。ビューを呼び出す作業。
Xシェア・動的OGP機能のキャッチアップ（テスト実装含む）に時間を取られそうです

**AIであるあるを生成**（〆：12/1, 12/8 ）
  - [ ]  **Open API を使うためのGemを調査・実装**
    - 未ログインユーザーがアプリをチュートリアルできる機能
    - Open AIのキャッチアップや実装は、２週間ほどと見積もってます

**投稿に関して**（〆：12/15（少人数に公開してFBを修正する期間を含む））
  - [ ] **投稿・検索フォームをオートコンプリート化** 　[Stimulus : オートコンプリート](https://github.com/afcapel/stimulus-autocomplete)
  - [ ] **投稿フォームに文字数カウンター機能**　[Stimulus : 文字数カウンター](https://www.stimulus-components.com/docs/stimulus-character-counter)   

**カリキュラムを振り返って実装できそうなもの**（〆：12/22, 12/29 ）
- [ ] **検索機能**：Rails基礎18
- [ ] **ハッシュタグ付け**：中間試験Rails課題1
- [ ] **ブックマーク登録**：Rails基礎14,15
- [ ] **i18n化**：Rails基礎4
  - i18n化：必須ではないが、そんな手間取るのものではないのでやっておくのが良い  
          Lintチェックが気になるなら、rubocopの設定を変更すればいい

🩷 **余裕があれば実装したいな程度に思ってる機能**（ 🟧 🟩 両方終わってから）
- [ ] 優先順位１：ページネーション：Rails基礎17
  -  参考記事：[`gem 'kaminari'` + Tailwind + DaisyUI でページネーションをカスタマイズ](https://qiita.com/yuki31100725/items/f8f3ddeaa990de342d11)
- [ ] 優先順位２：google ログインで取得したプロフィールのアイコンを表示・編集
- [ ] 優先順位３：タイトルを動的に：Rails基礎12

____
## 🟩 は本リリースに向けて実装する、義務的に実装すべき内容 

**以下は全てGitHub Actionsで行う**のかな？
と認識しておりますが、正しいでしょうか？（〆：25/01/12, 1/19 ）
（12/30~翌1/5は、基本的に年末年始休みとします。 その期間にも、余裕を見つけて準備や実装をするつもりです。）
　　参考記事：[GitHub Actionsでテストを自動化させてみた（Rspec、Rubocop）](https://qiita.com/kapi819/items/91589cd0145543b09325)
  - [ ] **RSpec**（`モデルテスト+システムテスト` or `モデルテスト+リクエストテスト`） 
  - [ ] **CI**（GitHubActions）
  - [ ] **Rubocopを使ってのリファクタリング**
 

以下は　〆：25/01/26
- [ ] **オートログイン**（再度ログイン操作を行わせない機能）
  - googleログインのトークンの保存・有効期限の詳細な管理設定を追加すべき
- [ ] **レスポンシブ対応**
  - 参考記事：[`grid` `grid-cols-1`](https://lazy-developer.jp/tailwindcss-responsive-design#:~:text=grid%20%E3%82%AF%E3%83%A9%E3%82%B9%E3%81%A8%20grid%2Dcols%2D1%20%E3%82%AF%E3%83%A9%E3%82%B9)　[ :tailwindcss: でレスポンシブ対応してみる](https://qiita.com/ryuta_okazaki13/items/cdd9793f7ab687a5ac40#%E4%BD%BF%E3%81%84%E6%96%B9)
- [ ] **独自ドメイン反映**
  - [お名前.com](https://cart.onamae.com/register/search/domain)、[X-server](https://www.xserver.ne.jp/)のどちらかを使おうかと思います。（希望は前者）
- [ ] **ローディングアニメーション**（処理が重い箇所）
  - 現時点で検証ツールのパフォーマンスを見ると`良好`と表示されるので、最後の最後でも良いかも？と思っています

**Comment by kenchasonakai** [comment]
> 以下は全てGitHub Actionsで行うのかな？

`GitHubActions上でも実行されるようにする`が正しいかと思います
CIまわさないと確認出来なくなってしまうのでDocker環境でも実行できるようにしておきましょう

**Comment by pakira-56A** [comment]
@kenchasonakai 了解しました！今後ともよろしくお願い致します
